name: Publish maven package
on: [ workflow_dispatch ]
jobs:
  publish-maven-package:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: graalvm
      - name: Configure maven
        run: |
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain integrized --domain-owner 130594009435 --region us-east-1 --query authorizationToken --output text`
          mkdir -p ~/.m2
          echo "
          <settings>
            <servers>
              <server>
                <id>codeartifact</id>
                <username>aws</username>
                <password>${CODEARTIFACT_AUTH_TOKEN}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>codeartifact</id>
                <activation>
                  <activeByDefault>true</activeByDefault>
                </activation>
                <repositories>
                  <repository>
                    <id>codeartifact</id>
                    <url>https://integrized-130594009435.d.codeartifact.us-east-1.amazonaws.com/maven/integrized/</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
          </settings>
          " > ~/.m2/settings.xml
      - name: Install all modules
        run: mvn clean install -Dorg.slf4j.simpleLogger.defaultLogLevel=error
      - name: Publish artifact
        run: mvn deploy
